//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class ProjectEntities : DbContext
{
    public ProjectEntities()
        : base("name=ProjectEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<asset> assets { get; set; }
    public virtual DbSet<creditCard> creditCards { get; set; }
    public virtual DbSet<Employee> Employees { get; set; }
    public virtual DbSet<Member> Members { get; set; }
    public virtual DbSet<Note> Notes { get; set; }
    public virtual DbSet<Stock> Stocks { get; set; }
    public virtual DbSet<Stock1> Stocks1 { get; set; }
    public virtual DbSet<UserCredit> UserCredits { get; set; }
}
